CREATE TABLE id_generator(
  biz_tag VARCHAR(128) NOT NULL PRIMARY KEY COMMENT '业务名',
  max_id  BIGINT(20) NOT NULL DEFAULT 1 COMMENT '当前最大id值',
  step INT(11) DEFAULT 100 COMMENT '批量取ID增加的步长',
  `describe` VARCHAR(256) COMMENT '描述',
  update_time DATETIME ON UPDATE CURRENT_TIMESTAMP
);